# Generated by Django 3.0.9 on 2020-08-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a question topic (e.g. Programming)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='A detailed description explaining the problem and attempted solutions', max_length=2000)),
                ('quanda_votes', models.CharField(help_text='Amount of Quanda votes (used to sort good and bad questions)', max_length=13)),
                ('status', models.CharField(choices=[('r', 'Resolved'), ('u', 'Unresolved')], default='u', help_text='Question Resolution', max_length=1)),
                ('date_created', models.DateField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ManyToManyField(help_text='Select a topic for this question', to='questionandanswers.Topic')),
            ],
            options={
                'ordering': ['date_created', 'quanda_votes'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='A detailed description providing the solution to a given question', max_length=2000)),
                ('quanda_votes', models.CharField(help_text='Amount of Quanda votes (used to sort good and bad answers)', max_length=13)),
                ('date_created', models.DateField(editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionandanswers.Question')),
            ],
            options={
                'ordering': ['quanda_votes', 'date_created'],
            },
        ),
    ]
