# Generated by Django 3.0.9 on 2020-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quanda_votes',
            field=models.CharField(default=0, help_text='Amount of Quanda votes (used to sort good and bad answers)', max_length=13),
        ),
        migrations.AlterField(
            model_name='question',
            name='quanda_votes',
            field=models.CharField(default=0, help_text='Amount of Quanda votes (used to sort good and bad questions)', max_length=13),
        ),
    ]
