# Generated by Django 3.0.9 on 2020-08-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0002_auto_20200806_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created', 'quanda_votes']},
        ),
    ]
