# Generated by Django 3.0.9 on 2020-08-06 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0003_auto_20200806_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quanda_votes', 'date_created']},
        ),
    ]
