# Generated by Django 3.0.9 on 2020-08-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0004_auto_20200806_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['date_created', 'quanda_votes']},
        ),
        migrations.AlterField(
            model_name='question',
            name='quanda_votes',
            field=models.IntegerField(default=0, help_text='Amount of Quanda votes (used to sort good and bad questions)'),
        ),
    ]
