# Generated by Django 3.0.9 on 2020-08-06 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0005_auto_20200806_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='quanda_votes',
            field=models.IntegerField(default=0, help_text='Amount of Quanda votes (used to sort good and bad answers)'),
        ),
    ]
