# Generated by Django 3.0.9 on 2020-08-07 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionandanswers', '0007_auto_20200806_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-quanda_votes', '-date_created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created', '-quanda_votes']},
        ),
    ]
